message("using FindDEMOLIB.cmake find demolib")

FIND_PATH(DEMOLIB_INCLUDE_DIR demo.h ${CMAKE_SOURCE_DIR})
message("DEMOLIB_INCLUDE_DIR:${DEMOLIB_INCLUDE_DIR}")

FIND_LIBRARY(DEMOLIB_LIBRARY libdemolib.a ${CMAKE_BINARY_DIR})
message("DEMOLIB_LIBRARY:${DEMOLIB_LIBRARY}")

if(DEMOLIB_INCLUDE_DIR AND DEMOLIB_LIBRARY)
    set(DEMOLIB_FOUND TRUE)
endif(DEMOLIB_INCLUDE_DIR AND DEMOLIB_LIBRARY)